### ISSUE TITLE
Updating a incident doesn't worrk

### ISSUE THREAD

**Issue by JonathanGailliez** [justmiles/node-gta-service-desk#1]
Hi,

first of all thanks a lot for putting this library together. It saves me a lot of time. 

I was playing around with the update of an incident and I get an error: 
```
Error: [E400] The incident parameter must be specified for this call
```

I also noticed that in your code:
```
updateIncident:(id, payload, callback) ->
    payload = incident: payload
    this.XHR "PUT", "/incidents/#{id}.json", null, null, callback
```
you never use the payload.

Might this be the issue or am I doing something wrong.

Thanks for your time.

Best regards,
Jonathan.

**Comment by justmiles** [comment]
Hi Jonathan,

Thanks for pointing that out. I've updated the `updateIncident` method to pass the payload. Much of this library has only been created and vetted as I needed them and since there's no test coverage yet I appreciate the extra eyes. 

Here's a quick example of updateIncident:

```javascript
serviceDesk.showIncident(100, function (res) {

    if (res) {
        var incident = res.incident;
        console.log(incident.title);
        incident.title = "Updating the title";

        serviceDesk.updateIncident(incident.id, incident, function(res) {
            console.log(res.incident.title); // prints "Updating the title"
        });
    }

});
```

If you have the time, pull requests are welcome.

Thanks,

Miles

**Comment by JonathanGailliez** [comment]
Hi thanks for the quick answer and the quick fix.

Next time I'll make sure to make a pull request if I come across something or I need something.

Best regards,
Jonathan.
